// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netgo.treeplanting.Infrastructure.Database;

#nullable disable

namespace netgo.treeplanting.Infrastructure.Migrations.DomainNotificationStoreDb
{
    [DbContext(typeof(DomainNotificationStoreDbContext))]
    partial class DomainNotificationStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("netgo.treeplanting.Domain.Core.DomainNotifications.StoredDomainNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AggregateId");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code");

                    b.Property<string>("Data")
                        .HasColumnType("varchar(350)")
                        .HasColumnName("Data");

                    b.Property<Guid>("DomainNotificationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DomainNotificationId");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Key");

                    b.Property<string>("MessageType")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MessageType");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("Timestamp");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Value");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("StoredDomainNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
